name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
version-template: '$MAJOR.$MINOR.$PATCH'

categories:
  - title: 'Breaking Changes'
    labels:
      - 'breaking changes'
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
      - 'fix'

version-resolver:
  major:
    labels:
      - 'breaking changes'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'fix'
  default: patch

autolabeler:
  - label: 'bug'
    branch:
      - '/fix.*/'
      - '/bugfix.*/'
      - '/hotfix.*/'
  - label: 'feature'
    branch:
      - '/feature.*/'
      - '/feat.*/'
  - label: 'enhancement'
    branch:
      - '/enhancement.*/'
      - '/improve.*/'

template: |
  ## Changes

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION