name: Conflict Marker Checker
description: Check if PR files contain conflict markers
author: VeyronSakai

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: alert-triangle
  color: red

# Define your inputs here.
inputs:
  github-token:
    description: GitHub token for API access
    required: true
    default: ${{ github.token }}
  exclude-patterns:
    description: Comma-separated list of file patterns to exclude from checking
    required: false
    default: ''

# Define your outputs here.
outputs:
  has-conflicts:
    description: Whether conflict markers were found (true/false)
  conflicted-files:
    description: Comma-separated list of files with conflicts

runs:
  using: node20
  main: dist/index.js
