name: Check for Conflict Markers

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for conflict markers
        uses: ./
        id: conflict-check
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR if conflicts found
        if: steps.conflict-check.outputs.has-conflicts == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const files = '${{ steps.conflict-check.outputs.conflicted-files }}'.split(',');
            const body = `⚠️ **Conflict markers detected!**\n\nThe following files contain conflict markers:\n${files.map(f => `- ${f}`).join('\n')}\n\nPlease resolve all conflicts before merging.`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
